### ISSUE TITLE
Update welcome screen on web site

### ISSUE THREAD

**Issue by clintkitson** [SuperKomputer/superkomputer.io#5]
It would be great to include another section at the bottom of the page that details the frameworks/tech we are using to build the project.

- Kubernetes
- Swagger (API definition and bindings)
- Go/NodeJS
- ZenHub (project tracking)
- Docker (application images)
.. others??

**Comment by gouravnayyar** [comment]
@clintkitson sure. I will add it.

**Comment by gouravnayyar** [comment]
@clintkitson 
Added the footer section which highlights the tech and framework used. 
<img width="1310" alt="screen shot 2018-03-28 at 11 08 03 am" src="https://user-images.githubusercontent.com/491740/38010851-6bc6836a-3278-11e8-806e-2f6492137c9a.png">
