### ISSUE TITLE
add consumer flow diagram

### ISSUE THREAD

**Issue by clintkitson** [SuperKomputer/superkomputer.io#6]
Should we add a consumer flow diagram?

https://docs.google.com/drawings/d/17fF5Hp-_GmdpoGCSaSIJVZ31rMuy8UvtbgAwUFo58fY/edit?usp=sharing

**Comment by gouravnayyar** [comment]
Yes, this would fit perfectly in the **How does it work? section**

 @clintkitson updated the consumer flow diagram.

![screencapture-localhost-3000-2018-03-28-11_36_37](https://user-images.githubusercontent.com/491740/38011842-a4145e28-327c-11e8-8369-90f23ef95b2b.png)
